# Generated by Django 3.1.4 on 2021-02-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminregi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_nm', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FilterDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterdataDate', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobileno', models.PositiveIntegerField(default='')),
                ('address', models.TextField(default='', max_length=1000)),
                ('store', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=50)),
                ('totalprice', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(blank=True, max_length=50)),
                ('PersonName', models.CharField(blank=True, max_length=50)),
                ('Contact', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('password', models.CharField(max_length=50)),
                ('add1', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('admin_nm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.adminregi')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=50)),
                ('productquantity', models.IntegerField()),
                ('date', models.DateField(auto_now=True, null=True)),
                ('store_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.storedetails')),
            ],
        ),
    ]
