# Generated by Django 3.1.4 on 2021-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210219_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
