# Generated by Django 3.1.4 on 2021-02-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_productdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregi',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
