# Generated by Django 3.1.4 on 2021-02-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210220_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregi',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='email',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app1.adminregi'),
        ),
    ]
