# Generated by Django 3.1.3 on 2021-02-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210220_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.adminregi'),
        ),
        migrations.CreateModel(
            name='SK_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(default='', max_length=200)),
                ('date_data', models.DateField(auto_now=True, null=True)),
                ('store_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.storedetails')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='Bills_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sk_bills'),
        ),
    ]
