# Generated by Django 3.1.3 on 2021-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210227_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='Bills_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
