# Generated by Django 3.1.3 on 2021-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210227_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk_bills',
            name='pd_nm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sk_bills',
            name='pd_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sk_bills',
            name='pd_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sk_bills',
            name='pd_tot',
            field=models.FloatField(default=0.0),
        ),
    ]
