# Generated by Django 3.1.3 on 2021-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210301_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
