# Generated by Django 2.1.5 on 2021-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210301_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk_bills',
            name='date_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
